language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  code_climate:
    repo_token: d123d50216561f0981293011c9c1505f48bac2b899e32c2e87062dd62a616928

before_script:
- composer install

after_script:
- vendor/bin/test-reporter